import os
import time

print ('E/')
time.sleep(0.5)
os.system('clear')
print ('E|')
time.sleep(0.5)
os.system('clear')
print ('EZ/')
time.sleep(0.5)
os.system('clear')
print ('EZ|')
time.sleep(0.5)
os.system('clear')
print ('EZZ/')
time.sleep(0.5)
os.system('clear')
print ('EZZ|')
time.sleep(0.5)
os.system('clear')
print ('EZZA/')
time.sleep(0.5)
os.system('clear')
print ('EZZA|')
time.sleep(0.5)
os.system('clear')
print ('EZZA H/')
time.sleep(0.5)
os.system('clear')
print ('EZZA H|')
time.sleep(0.5)
os.system('clear')
print ('EZZA H /')
time.sleep(0.5)
os.system('clear')
print ('EZZA HI|')
time.sleep(0.5)
os.system('clear')
print ('EZZA HI/')
time.sleep(0.5)
os.system('clear')
print ('EZZA HI|')
time.sleep(0.5)
os.system('clear')
print ('EZZA HI/')
time.sleep(0.5)
os.system('clear')
print ('EZZA HIR|')
time.sleep(0.5)
os.system('clear')
print ('EZZA HIR/')
time.sleep(0.5)
os.system('clear')
print ('EZZA HIRO|')
time.sleep(0.5)
os.system('clear')
print ('EZZA HIRO/')
time.sleep(0.5)
os.system('clear')
print ('EZZA HIROC|')
time.sleep(0.5)
os.system('clear')
print ('EZZA HIROC/')
time.sleep(0.5)
os.system('clear')
print ('EZZA HIROCHI|')
time.sleep(0.5)
os.system('clear')
print ('EZZA HIROCHI/')
time.sleep(0.5)
os.system('clear')
print ('EZZA HIROCHI')
time.sleep(0.5)
© 2021 GitHub, Inc.
